### PR TITLE
Fix parenthesis placement

### LINKED ISSUE #391: id never gets added to form
surprising no one has found this before.

these lines need to be changed:

https://github.com/lat9/one_page_checkout/blob/3ae4927a680491eee9fe11ca28a6e7c821445bc1/includes/templates/template_default/templates/tpl_checkout_one_confirmation_default.php#L195-L200

```
<?= zen_draw_form('checkout_confirmation', $form_action_url, 'post', 'id="checkout_confirmation"' . (($confirmation_required) ? ' onsubmit="submitonce();"' : ''));  ?>
```

the string concatenation was taken precedence over the conditional, therefore the id tag never made it onto the form.  which is no doubt not intended.  therefore the extra parenthesis are needed.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #391

### CODE REVIEW

File: includes/templates/template_default/templates/tpl_checkout_one_confirmation_default.php [hunk 1]
```diff
@@ -211,4 +211,4 @@
 <?php echo '</form>'; ?>
 
     <div id="checkoutOneConfirmationLoading" style="display: none;"><?php echo ((CHECKOUT_ONE_CONFIRMATION_INSTRUCTIONS === '') ? '' : (CHECKOUT_ONE_CONFIRMATION_INSTRUCTIONS . '<br><br>')) . zen_image($template->get_template_dir(CHECKOUT_ONE_CONFIRMATION_LOADING, DIR_WS_TEMPLATE, $current_page_base ,'images') . '/' . CHECKOUT_ONE_CONFIRMATION_LOADING, CHECKOUT_ONE_CONFIRMATION_LOADING_ALT); ?></div>
-</div>
\ No newline at end of file
+</div>
```
Comment (drbyte) [inline includes/templates/template_default/templates/tpl_checkout_one_confirmation_default.php:214]: NB: Github auto-added the line-break to the end of the file.

Comment (lat9) [reply includes/templates/template_default/templates/tpl_checkout_one_confirmation_default.php:214]: I'll accept this but then un-close the issue.  My preference is to keep issues open until release.
